### ISSUE TITLE
peanutStream2 crash when starts

### ISSUE THREAD

**Issue by tweetytsui** [uml-robotics/ros_tango_native_stream#6]
Hi, 
I have builded the brach "yellowstone Updated Nov 25, 2015 by carlosjoan91" successfully,
the ndk version is r10c,  build platform is ubuntu14.04 in virtual machine of mac,
device is tango project tablet with android 4.4.2, 
The app crashed after Tango API starting message appeared for a while, I can input the robot URI when apk started up, other official Tango apps work fine.
I'm new in android development and I have no idea how to debug it, 
any idea about this issue ?

**Comment by tweetytsui** [comment]
I solved the problem that peanutstream2 crached after typing the URI, 
using the newest C API from google developer site always caused the crash problem.
I donwload the old API from https://github.com/googlesamples/tango-examples-c and rebuild app,
now it works and I can see odom and depth cloud in RVIZ.

**Comment by carlosjoan91** [comment]
Thanks for the report, I have not updated the app to be completely compatible with the new library because I am in the process of switching to roscpp running natively, instead of rosjava. As soon as that version is ready I will upload it, that one will have support for the new Tango library. In the meantime, as you discovered, the best workaround is to use the old library.

**Comment by carlosjoan91** [comment]
The version I mentioned on the last comment using the NDK version of ros is now available if you want to try that one https://github.com/uml-robotics/tango_ros_ndk , it's still a WIP, but should be much more stable than this one.
